### ISSUE TITLE
Scrum Update - 12/08/2022

### ISSUE THREAD

**Issue by anan899** [RamitKataria/meeting-planner#72]

**Comment by anan899** [comment]
May Tang(t1n1b)

(1) what you’ve worked on in the previous two weeks:
- mainly work on the function for "import ICS"

(2)what you’ll be working on in the next two weeks:
- Maybe I'll work on the SendEmail button to notify all attendees in the meeting 
- Modify the "Import ICS" function a little bit, to make sure that it will not crash due to any timezone problem

(3) where you might have gotten stuck during the last two weeks:
-Our function for importing ICS files was not working when deploying our app on Heroku, but it works locally. This is because we use getHours() in a for loop to find all the slots for the meeting time range in our function. But getHour() only return local time. When the timezone changes,  the for loop to find all the slots may not work.
So we use another function called getTime() in the for loop, which returns the number of milliseconds since January 1, 1970, UTC. The result it returns will not change if the timezone changes. Then the whole function work.

**Comment by merlin217** [comment]
Tom Mo(c9j7l)
(1) What you've worked on in the previous two weeks: 

- Refactor frontend code & backend endpoints for meeting creation & availability page to be in line with backend refactoring
- Implemented multi time zone functionality
- Troubleshoot deployment-specific bugs

(2) What you'll be working on in the next two weeks: 

- Distribute the deployed app for user feedback
- Fully support guest users

(3) Where you might have gotten stuck during the last two weeks:

- Dealing with time zones. Learned from painful mistakes not to mess with time zone offsets, and interact with the UTC timestamp whenever possible; converting to user-side time zone should always be the last step. 
- Server refactoring introduced changes, so a significant amount of time was spent restoring past functionalities

**Comment by RamitKataria** [comment]
Ramit Kataria (x7x2b)

> 1. What did you work on this past iteration (2 weeks)?
- Verification of user ID with the JWT tokens
- Refactoring for more robustness and better responses on errors
- Documentation
- Final code cleanup
- Adding checks for built-in mongoDB fields to not expose them to the user

> 2. What were any major issues/challenges you ran into?
- Debugging unexpected endpoint responses
- Deciding on a workflow for user creation

> 3. What do you plan to work on for this coming iteration (2 weeks)?
- Refactor the client-side code to make it more robust and clean
- Adding a new layout for availability selection
- Endpoints for sending email notifications with included ics file
- Add more authentication options
- See if we can do something about the client previews using the prod server instead of the preview server
- Refactor the function that imports users' personal calendar to make it cleaner and more error-resistant

**Comment by sophiechai** [comment]
Sophie Chai (l4h6k)
(1) What you've worked on in the previous two weeks:
- Refactored frontend and backend code to using firebase IDs.
- Testing the workflow and fix bugs.

(2) What you'll be working on in the next two weeks:
- Worked on guest account features
- Allow organizers to finalize meeting date and time

(3) Where you might have gotten stuck during the last two weeks:
Figuring out the grid structure of Availability page to restructure the layouts to cater smaller screens.
Putting together May's calendar feature into Availability Page.
